# Generated by Django 5.1.6 on 2025-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('firefighter', 'Firefighter'), ('team_leader', 'Team Leader'), ('equipment_manager', 'Equipment Manager'), ('safety_officer', 'Safety Officer'), ('paramedic', 'Paramedic'), ('driver', 'Driver')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
