# Generated by Django 5.1.6 on 2025-05-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_control', '0002_teammember_contact_number_teammember_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('firefighter', 'Firefighter'), ('team_leader', 'Team Leader'), ('equipment_manager', 'Equipment Manager'), ('safety_officer', 'Safety Officer'), ('paramedic', 'Paramedic'), ('driver', 'Driver'), ('firewatch', 'FireWatch')], max_length=50, null=True),
        ),
    ]
