# Generated by Django 5.1.6 on 2025-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_control', '0003_alter_teammember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealert',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='firealert',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('firefighter', 'Firefighter'), ('firewatch', 'FireWatch'), ('team_leader', 'Team Leader'), ('equipment_manager', 'Equipment Manager'), ('safety_officer', 'Safety Officer'), ('paramedic', 'Paramedic'), ('driver', 'Driver')], max_length=50, null=True),
        ),
    ]
